#cloud-config
package_update: true
packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
  - curl

write_files:
  # Write Caddy config to a temporary spot
  - path: /tmp/MyCaddyfile
    content: |
      balancing.bremm.dev {
        # Serve site with TLS with downloaded certs
        tls /etc/caddy/certs/fullchain.pem /etc/caddy/certs/privkey.pem

        root * /var/www/memcaydia
        encode gzip
        try_files {path} /index.html #fallback for SPA
        file_server

        # unique server ID header for each VM
        header {
          X-Server-ID __SERVER_ID__
        }
      }

  # Script to download site content from Azure Blob Storage
  - path: /opt/scripts/download_site.sh
    permissions: "755"
    content: |
      #!/bin/bash
      set -euo pipefail

      # This tells azcopy to use managed identity WITHOUT needing cached login
      export AZCOPY_AUTO_LOGIN_TYPE=MSI

      DEST="/var/www/memcaydia/"
      SOURCE="https://memcaydiasitedata.blob.core.windows.net/dist/"

      # Ensure correct ownership & permissions (idempotent)
      mkdir -p "$DEST"
      chown -R caddy:www-data "$DEST"
      chmod -R 775 "$DEST"

      # Download sites files using AzCopy
      azcopy sync \
        "$SOURCE" \
        "$DEST" \
        --recursive \
        --delete-destination=true
      systemctl reload caddy

  # Systemd service to sync site content
  - path: /etc/systemd/system/site-sync.service
    content: |
      [Unit]
      Description=Sync site content from Azure Blob Storage
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/opt/scripts/download_site.sh
      User=root
      Group=root

  - path: /etc/systemd/system/site-sync.timer
    content: |
      [Unit]
      Description=Run site sync every 15 minutes

      [Timer]
      OnBootSec=2min
      OnUnitActiveSec=15min
      RandomizedDelaySec=60
      Persistent=true

      [Install]
      WantedBy=timers.target

runcmd:
  # Install AzCopy (Azure VMs don't always have it by default)
  - wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1 && cp ./azcopy /usr/bin/
  - chmod +x /usr/bin/azcopy

  # Log in to AzCopy using the VM's managed identity
  - azcopy login --identity

  # Download TLS certificates from Blob Storage by logging in with the VM's managed identity
  - mkdir -p /etc/caddy/certs
  - azcopy copy 'https://memcaydiasitedata.blob.core.windows.net/cert/fullchain.pem' '/etc/caddy/certs/'
  - azcopy copy 'https://memcaydiasitedata.blob.core.windows.net/cert/privkey.pem' '/etc/caddy/certs/'

  # Install Caddy
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  - apt-get update
  - apt-get install caddy -y

  # Set cert permissions AFTER caddy user exists
  - chown -R caddy:caddy /etc/caddy/certs
  - chmod 600 /etc/caddy/certs/privkey.pem

  # Overwrite the default Caddyfile with our own
  - mv /tmp/MyCaddyfile /etc/caddy/Caddyfile
  - systemctl restart caddy

  # Stop Caddy, sync content, then start
  - systemctl stop caddy
  - /opt/scripts/download_site.sh
  - systemctl start caddy

  # Enable and start the site sync timer
  - systemctl daemon-reload
  - systemctl enable --now site-sync.timer
